Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "dockerlocal"
  config.vm.network "private_network", ip: "192.168.200.9"
  config.vm.provider :virtualbox do |vb|
	vb.customize [ 'modifyvm', :id, '--name', 'dockerlocal']
    vb.customize [ 'modifyvm', :id, '--memory', '386' ]
	vb.customize [ 'modifyvm', :id, '--cpus', '1' ]
  end 
  config.vm.provision "docker" do |d|
	d.build_image "/vagrant/app"
  end
end

